### ISSUE TITLE
[Newsletter] add new way to inject custom Address Source Adapter

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore-5-issues#55]
via services or same way like to add custom data types... 
https://github.com/pimcore/pimcore-5/blob/symfony/doc/Development_Documentation/03_Documents/02_Document_Types/05_Newsletter_Documents.md#creating-a-custom-address-source-adapter

**Comment by brusch** [comment]
This issue was moved to pimcore/pimcore#1397
